# Site settings
title: tl;dr{Code}
email: webmaster@tldrcode.com
description: >
  Don't waste time with syntax; unleash the code!
baseurl: ""
url: "http://tldrcode.com"
twitter_username: https://twitter.com/tldrcode
github_username:  https://github.com/tldrcode
github_repo:  https://github.com/tldrcode/tldrcode.com

# Build settings
markdown: kramdown

highlighter: pygments

collections:
  languages:
    output: true
  tools:
    output: true

permalink: /topics/:title

permalink: /topics/:title

exclude: ['README.md', 'Vagrantfile', 'CNAME', 'LICENSE', '_languages/template.markdown']
